#https://devopscube.com/setup-ingress-kubernetes-nginx-controller/
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "service.name" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: poc.spaceinje.com
    http:
      paths:
      - path: /
        backend:	
          serviceName: example-service
          servicePort: 80

