#https://devopscube.com/setup-ingress-kubernetes-nginx-controller/
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "service.name" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: service.atlan.spaceinje.com
    http:
      paths:
      - path: /
        backend:	
          serviceName: example-service
          servicePort: 80
  - host: sonarqube.atlan.spaceinje.com
    http:
      paths:
      - path: /
        backend:	
          serviceName: sonarqube-sonarqube
          servicePort: 9000
  - host: concourse.atlan.spaceinje.com
    http:
      paths:
      - path: /
        backend:	
          serviceName: concourse-web
          servicePort: 8080

  - host: prometheus.atlan.spaceinje.com
    http:
      paths:
      - path: /
        backend:	
          serviceName: prometheus-server
          servicePort: 80
