--- 
jobs: 
  - 
    name: build-job
    plan: 
      - 
        get: example-service-git-sources
        trigger: true
      - 
        config: 
          image_resource: 
            source: 
              repository: python
              tag: 3.6
            type: docker-image
          inputs: 
            - 
              name: example-service-git-sources
          platform: linux
          run: 
            args: 
              - "-exc"
              - |
                  pip3 install -r example-service-git-sources/app/src/requirements.txt
                  python3 example-service-git-sources/app/src/test_app.py
            path: sh
        task: execute_build_test
    public: true
    on_failure:
      put: slack-alert
      params:
        channel: '#sripathi'
        username: 'concourse'
        icon_emoji: ':concourse:'
        silent: true
        text: |
              build job failure message
    on_success:
      put: slack-alert
      params:
        channel: '#sripathi'
        username: 'concourse'
        icon_emoji: ':concourse:'
        silent: true
        text: |
            build job success message        
resources: 
  - 
    name: example-service-git-sources
    source: 
      branch: develop
      password: {{git_password}}
      uri: https://bitbucket.org/sripathi2610/example-service.git
      username: {{git_user}}
    type: git
  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack_notification_url}}    
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: v1.3.0