--- 
jobs: 
  - 
    name: build-job
    plan: 
      - 
        get: example-service-git-sources
        trigger: true
      - 
        config: 
          image_resource: 
            source: 
              repository: python
              tag: 3.6
            type: docker-image
          inputs: 
            - 
              name: example-service-git-sources
          outputs: 
            - 
              name: pylint.txt
            - 
              name: coverage.xml	      
          platform: linux
          run: 
            args: 
              - "-exc"
              - |
                  echo "Running pylint"
                  pip3 install -r example-service-git-sources/app/src/requirements.txt		  
                  pylint example-service-git-sources/app/src/*.py > pylint.txt || true
                  coverage run example-service-git-sources/app/src/*.py || true
                  coverage xml example-service-git-sources/app/src/*.py || true
                  coverage report -m example-service-git-sources/app/src/*.py || true		  
                  python3 example-service-git-sources/app/src/test_app.py
            path: sh
        task: execute_build_test
      - 
        config: 
          image_resource: 
            source: 
              repository: ksripathi/sonar-scanner
              tag: latest
            type: docker-image
          inputs: 
            - 
              name: pylint.txt
            - 
              name: example-service-git-sources	      
            - 
              name: coverage.xml	      
          platform: linux
          run: 
            args: 
              - "-exc"
              - |
                  cd example-service-git-sources
		  sonar-scanner
            path: sh
        task: run_sonar_scanning_steps
    public: true
    on_failure:
      put: slack-alert
      params:
        channel: '#sripathi'
        username: 'concourse'
        icon_emoji: ':concourse:'
        silent: true
        text: |
              build job failure message
    on_success:
      put: slack-alert
      params:
        channel: '#sripathi'
        username: 'concourse'
        icon_emoji: ':concourse:'
        silent: true
        text: |
            build job success message
resource_types:
- name: slack-notification
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.3.0
  type: docker-image	    
resources:
- name: example-service-git-sources
  source:
    branch: develop
    password: sudswathi1993&
    uri: https://bitbucket.org/sripathi2610/example-service.git
    username: sripathi2610
  type: git
- name: slack-alert
  source:
    url: https://hooks.slack.com/services/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
  type: slack-notification