---
resources:
- name: example-service-git-repo
  type: git
  source:
    uri: https://bitbucket.org/sripathi2610/example-service.git
    branch: develop
    username: {{git_user}}
    password: {{git_password}}

- name: example-service-docker-image
  type: docker-image
  source:
    email: kammari.sripathi@gmail.com
    username: {{docker_user}}
    password: {{docker_password}}
    repository: ksripathi/example-service
- name: example-tools-image
  type: docker-image
  source:
    email: kammari.sripathi@gmail.com
    username: {{docker_user}}
    password: {{docker_password}}
    repository: ksripathi/example-tools-image
jobs: 
  - 
    name: publish-docker-image
    plan: 
      - 
        get: example-service-git-repo
      - 
        params: 
          build: example-service-git-repo/app
        put: example-service-docker-image
    public: true
    serial: true
  - 
    name: publish-tools-docker-image
    plan: 
      - 
        get: example-service-git-repo
      - 
        params: 
          build: example-service-git-repo/tools-docker-image
        put: example-tools-image
    public: true
    serial: true    
  - 
    name: dev-deploy-job
    plan: 
      - 
        get: example-service-git-repo
        passed: [publish-docker-image]
        trigger: true
      - 
        config: 
          image_resource: 
            source: 
              repository: ksripathi/example-tools-image
            type: docker-image
          inputs: 
            - 
              name: example-service-git-repo
          platform: linux
          run: 
            args: 
              - "-exc"
              - |
                  echo {{service_account}} > service_account.json
                  gcloud auth activate-service-account --key-file=service_account.json
                  gcloud container clusters get-credentials devcluster --region us-central1 --project dev-project-259009
                  kubectl -n kube-system create serviceaccount tiller || true		  
                  kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller || true
                  helm init --service-account tiller || true
                  cd example-service-git-repo/helm-chart
                  helm install . --generate-name
            path: sh
        task: dev-deploy-job
    public: true
